version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ssh-tunnel-manager_web_1
      APP_PORT: 5000
    container_name: aquaspy-sshtunnelmanager_app_proxy_1

  web:
    image: theselfhostingart/ssh-tunnel-manager:v1.2
    restart: on-failure
    user: "1000:1000"  # Run as UID 1000, GID 1000
    stop_grace_period: 1m
    volumes:
      - ssh-data:/data
    environment:
      - TZ=UTC
    extra_hosts:               #  <‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑
      - "host.docker.internal:host-gateway"
    container_name: ssh-tunnel-manager_web_1

volumes:
  ssh-data:
    name: ssh-tunnel-manager-data

