version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ssh-tunnel-manager_1
      APP_PORT: 5000

  web:
    image: theselfhostingart/ssh-tunnel-manager:v1.0
    restart: on-failure
    user: "1000:1000"  # Run as UID 1000, GID 1000
    stop_grace_period: 1m
    # Either remove the ports section entirely if not needed
    # or uncomment and provide actual port mappings:
    # ports:
    #   - "5000:5000"
    volumes:
      - ssh-data:/data
    environment:
      - TZ=UTC

volumes:
  ssh-data:
    name: ssh-tunnel-manager-data
